services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./.mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  redis-cache:
    image: redis
    ports:
      - 6379:6379
volumes:
  pgdata:
    driver: local
